### PR TITLE
Add the `IBM i Project Explorer` and `Source Orbit` extension

### PR DESCRIPTION
**Pull request by SanjulaGanepola**

### CODE REVIEW

**Comment by edmundreinhardt** [comment]
I have been looking forward to this PR for some time.  Is there any concerns?

**Comment by edmundreinhardt** [comment]
@worksofliam could we approve and merge?
@ThePrez was asking for this yesterday

**Comment by edmundreinhardt** [comment]
Any updates? Can we approve.  We wll be talking Source Orbit and IBM i Project explorer multiple times as the Navigate conference and it would nice to have the Development Pak seal of approval.  Are there any blockers?
@worksofliam

**Comment by worksofliam** [comment]
Since @SanjulaGanepola confirmed with me that the library list doesn't get disabled unless iproj.json is created I think it could be merged.

What do you think @sebjulliand?

**Comment by edmundreinhardt** [comment]
@sebjulliand Hi Seb, do you have an objection to merging this PR?

**Comment by edmundreinhardt** [comment]
@sebjulliand Sorry to be a pain, just looking for some response on this

**Comment by sebjulliand** [comment]
Sorry about the delay @edmundreinhardt ; so if Project Explorer doesn't interfer with anything unless an i Project is open, I don't have any object to have it included in the dev pack 👍🏻

**Review by sebjulliand — APPROVED** [review]
Looks good to me!

**Comment by AIforIBMi** [comment]
@worksofliam we have approval, can we merge this PR now?

**Pull request merged**
